name: Docker image build and publish
on:
  workflow_dispatch:
    inputs:
      path_to_dockerfile_ui:
        description: Path to the dockerfile (default = 'Dockerfile')
        default: "frontend/dockerfile"
        type: string
      path_to_dockerfile_backend:
        description: Path to the dockerfile (default = 'Dockerfile')
        default: "backend/dockerfile"
        type: string
      docker_backend_build_dir:
        description: Docker backend build directory (default = '.')
        default: "backend"
        type: string
      backend_image_tag:
        description: Tag to apply to images.
        type: string
        default: backend-artifact
      aws_account_id:
        description: AWS Account ID
        type: string
      aws_region:
        description: Target AWS Region
        default: "us-east-1"
        type: string
      ecr_repo_name:
        description: ecr repo name
        default: "mlopsbackend"
        type: string
      ml_model_run_id:
        description: mlflow run id where the model was logged
        default: ""
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      backend_image_tag: ${{ steps.build-publish-backend.outputs.backend_image_tag }}
      backend_full_image: ${{ steps.build-publish-backend.outputs.full_image }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          mask-password: 'false'

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-publish-backend
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo_name }}
          IMAGE_TAG: ${{ inputs.backend_image_tag }}
        run: |
          docker build "${{ inputs.docker_backend_build_dir }}" -f "${{ inputs.path_to_dockerfile_backend }}" --build-arg ML_MODEL_RUN_ID="${{ inputs.ml_model_run_id }}" -t "$ECR_REGISTRY/g8n4d6q1/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"